language: php

php: 
  - 5.3
  - 5.4
  - 5.5
before_install:
  - curl http://apt.basho.com/gpg/basho.apt.key | sudo apt-key add -
  - sudo bash -c "echo deb http://apt.basho.com $(lsb_release -sc) main > /etc/apt/sources.list.d/basho.list"
  - sudo apt-get update
  - "yes n | sudo apt-get install riak"
  - ulimit -n 2048
  - sudo service riak start
before_script:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --dev

script: phpunit